const ir = @import("../ir.zig");
const dispatch = @import("../../vm/dispatch.zig");
const ops = @import("ops.zig");

const Op = ir.Op;
const Slot = ir.Slot;
const HANDLER_SIZE = dispatch.HANDLER_SIZE;

pub fn instrSize(op: Op) usize {
    const ops_size: usize = switch (op) {
        .unreachable_ => @sizeOf(ops.OpsNone),
        .const_i32 => @sizeOf(ops.OpsConstI32),
        .const_i64 => @sizeOf(ops.OpsConstI64),
        .const_f32 => @sizeOf(ops.OpsConstF32),
        .const_f64 => @sizeOf(ops.OpsConstF64),
        .const_v128 => @sizeOf(ops.OpsConstV128),
        .const_ref_null => @sizeOf(ops.OpsDst),
        .ref_is_null => @sizeOf(ops.OpsDstSrc),
        .ref_func => @sizeOf(ops.OpsRefFunc),
        .ref_eq => @sizeOf(ops.OpsDstLhsRhs),
        .local_get => @sizeOf(ops.OpsLocalGet),
        .local_set => @sizeOf(ops.OpsLocalSet),
        .global_get => @sizeOf(ops.OpsGlobalGet),
        .global_set => @sizeOf(ops.OpsGlobalSet),
        .copy => @sizeOf(ops.OpsCopy),
        .copy_jump_if_nz => @sizeOf(ops.OpsCopyJumpIfNz),
        .jump => @sizeOf(ops.OpsJump),
        .jump_if_z => @sizeOf(ops.OpsJumpIfZ),
        .jump_if_nz => @sizeOf(ops.OpsJumpIfZ),
        .jump_table => @sizeOf(ops.OpsJumpTable),
        .select => @sizeOf(ops.OpsSelect),
        .ret => @sizeOf(ops.OpsRet),
        .i32_add_ret, .i32_sub_ret, .i64_add_ret, .i64_sub_ret => @sizeOf(ops.OpsLhsRhs),

        .f32_add_ret, .f32_sub_ret, .f64_add_ret, .f64_sub_ret => @sizeOf(ops.OpsLhsRhs),

        .i32_add,
        .i32_sub,
        .i32_mul,
        .i32_div_s,
        .i32_div_u,
        .i32_rem_s,
        .i32_rem_u,
        .i32_and,
        .i32_or,
        .i32_xor,
        .i32_shl,
        .i32_shr_s,
        .i32_shr_u,
        .i32_rotl,
        .i32_rotr,
        .i64_add,
        .i64_sub,
        .i64_mul,
        .i64_div_s,
        .i64_div_u,
        .i64_rem_s,
        .i64_rem_u,
        .i64_and,
        .i64_or,
        .i64_xor,
        .i64_shl,
        .i64_shr_s,
        .i64_shr_u,
        .i64_rotl,
        .i64_rotr,
        .f32_add,
        .f32_sub,
        .f32_mul,
        .f32_div,
        .f32_min,
        .f32_max,
        .f32_copysign,
        .f64_add,
        .f64_sub,
        .f64_mul,
        .f64_div,
        .f64_min,
        .f64_max,
        .f64_copysign,
        .i32_eq,
        .i32_ne,
        .i32_lt_s,
        .i32_lt_u,
        .i32_gt_s,
        .i32_gt_u,
        .i32_le_s,
        .i32_le_u,
        .i32_ge_s,
        .i32_ge_u,
        .i64_eq,
        .i64_ne,
        .i64_lt_s,
        .i64_lt_u,
        .i64_gt_s,
        .i64_gt_u,
        .i64_le_s,
        .i64_le_u,
        .i64_ge_s,
        .i64_ge_u,
        .f32_eq,
        .f32_ne,
        .f32_lt,
        .f32_gt,
        .f32_le,
        .f32_ge,
        .f64_eq,
        .f64_ne,
        .f64_lt,
        .f64_gt,
        .f64_le,
        .f64_ge,
        => @sizeOf(ops.OpsDstLhsRhs),

        .i32_clz,
        .i32_ctz,
        .i32_popcnt,
        .i32_eqz,
        .i64_clz,
        .i64_ctz,
        .i64_popcnt,
        .i64_eqz,
        .f32_abs,
        .f32_neg,
        .f32_ceil,
        .f32_floor,
        .f32_trunc,
        .f32_nearest,
        .f32_sqrt,
        .f64_abs,
        .f64_neg,
        .f64_ceil,
        .f64_floor,
        .f64_trunc,
        .f64_nearest,
        .f64_sqrt,
        .i32_wrap_i64,
        .i32_trunc_f32_s,
        .i32_trunc_f32_u,
        .i32_trunc_f64_s,
        .i32_trunc_f64_u,
        .i64_extend_i32_s,
        .i64_extend_i32_u,
        .i64_trunc_f32_s,
        .i64_trunc_f32_u,
        .i64_trunc_f64_s,
        .i64_trunc_f64_u,
        .i32_trunc_sat_f32_s,
        .i32_trunc_sat_f32_u,
        .i32_trunc_sat_f64_s,
        .i32_trunc_sat_f64_u,
        .i64_trunc_sat_f32_s,
        .i64_trunc_sat_f32_u,
        .i64_trunc_sat_f64_s,
        .i64_trunc_sat_f64_u,
        .f32_convert_i32_s,
        .f32_convert_i32_u,
        .f32_convert_i64_s,
        .f32_convert_i64_u,
        .f32_demote_f64,
        .f64_promote_f32,
        .f64_convert_i32_s,
        .f64_convert_i32_u,
        .f64_convert_i64_s,
        .f64_convert_i64_u,
        .i32_reinterpret_f32,
        .i64_reinterpret_f64,
        .f32_reinterpret_i32,
        .f64_reinterpret_i64,
        .i32_extend8_s,
        .i32_extend16_s,
        .i64_extend8_s,
        .i64_extend16_s,
        .i64_extend32_s,
        => @sizeOf(ops.OpsDstSrc),

        .i32_add_imm,
        .i32_sub_imm,
        .i32_mul_imm,
        .i32_and_imm,
        .i32_or_imm,
        .i32_xor_imm,
        .i32_shl_imm,
        .i32_shr_s_imm,
        .i32_shr_u_imm,
        .i32_eq_imm,
        .i32_ne_imm,
        .i32_lt_s_imm,
        .i32_lt_u_imm,
        .i32_gt_s_imm,
        .i32_gt_u_imm,
        .i32_le_s_imm,
        .i32_le_u_imm,
        .i32_ge_s_imm,
        .i32_ge_u_imm,
        => @sizeOf(ops.OpsBinopImm),

        .i64_add_imm,
        .i64_sub_imm,
        .i64_mul_imm,
        .i64_and_imm,
        .i64_or_imm,
        .i64_xor_imm,
        .i64_shl_imm,
        .i64_shr_s_imm,
        .i64_shr_u_imm,
        .i64_eq_imm,
        .i64_ne_imm,
        .i64_lt_s_imm,
        .i64_lt_u_imm,
        .i64_gt_s_imm,
        .i64_gt_u_imm,
        .i64_le_s_imm,
        .i64_le_u_imm,
        .i64_ge_s_imm,
        .i64_ge_u_imm,
        => @sizeOf(ops.OpsBinopImm64),

        .f32_add_imm,
        .f32_sub_imm,
        .f32_mul_imm,
        .f32_div_imm,
        => @sizeOf(ops.OpsBinopImmF32),

        .f64_add_imm,
        .f64_sub_imm,
        .f64_mul_imm,
        .f64_div_imm,
        => @sizeOf(ops.OpsBinopImmF64),

        .i32_add_imm_r,
        .i32_sub_imm_r,
        .i32_mul_imm_r,
        .i32_and_imm_r,
        .i32_or_imm_r,
        .i32_xor_imm_r,
        .i32_shl_imm_r,
        .i32_shr_s_imm_r,
        .i32_shr_u_imm_r,
        => @sizeOf(ops.OpsBinopImmR0),

        .i64_add_imm_r,
        .i64_sub_imm_r,
        .i64_mul_imm_r,
        .i64_and_imm_r,
        .i64_or_imm_r,
        .i64_xor_imm_r,
        .i64_shl_imm_r,
        .i64_shr_s_imm_r,
        .i64_shr_u_imm_r,
        => @sizeOf(ops.OpsBinopImmR064),

        .i32_eq_jump_if_false,
        .i32_ne_jump_if_false,
        .i32_lt_s_jump_if_false,
        .i32_lt_u_jump_if_false,
        .i32_gt_s_jump_if_false,
        .i32_gt_u_jump_if_false,
        .i32_le_s_jump_if_false,
        .i32_le_u_jump_if_false,
        .i32_ge_s_jump_if_false,
        .i32_ge_u_jump_if_false,
        => @sizeOf(ops.OpsCompareJump),

        .i32_eqz_jump_if_false => @sizeOf(ops.OpsEqzJump),

        .i64_eq_jump_if_false,
        .i64_ne_jump_if_false,
        .i64_lt_s_jump_if_false,
        .i64_lt_u_jump_if_false,
        .i64_gt_s_jump_if_false,
        .i64_gt_u_jump_if_false,
        .i64_le_s_jump_if_false,
        .i64_le_u_jump_if_false,
        .i64_ge_s_jump_if_false,
        .i64_ge_u_jump_if_false,
        => @sizeOf(ops.OpsCompareJump),

        .i64_eqz_jump_if_false => @sizeOf(ops.OpsEqzJump),

        .f32_eq_jump_if_false,
        .f32_ne_jump_if_false,
        .f32_lt_jump_if_false,
        .f32_gt_jump_if_false,
        .f32_le_jump_if_false,
        .f32_ge_jump_if_false,
        .f64_eq_jump_if_false,
        .f64_ne_jump_if_false,
        .f64_lt_jump_if_false,
        .f64_gt_jump_if_false,
        .f64_le_jump_if_false,
        .f64_ge_jump_if_false,
        => @sizeOf(ops.OpsCompareJump),

        .i32_eq_jump_if_true,
        .i32_ne_jump_if_true,
        .i32_lt_s_jump_if_true,
        .i32_lt_u_jump_if_true,
        .i32_gt_s_jump_if_true,
        .i32_gt_u_jump_if_true,
        .i32_le_s_jump_if_true,
        .i32_le_u_jump_if_true,
        .i32_ge_s_jump_if_true,
        .i32_ge_u_jump_if_true,
        => @sizeOf(ops.OpsCompareJump),

        .i32_eqz_jump_if_true => @sizeOf(ops.OpsEqzJump),

        .i64_eq_jump_if_true,
        .i64_ne_jump_if_true,
        .i64_lt_s_jump_if_true,
        .i64_lt_u_jump_if_true,
        .i64_gt_s_jump_if_true,
        .i64_gt_u_jump_if_true,
        .i64_le_s_jump_if_true,
        .i64_le_u_jump_if_true,
        .i64_ge_s_jump_if_true,
        .i64_ge_u_jump_if_true,
        => @sizeOf(ops.OpsCompareJump),

        .i64_eqz_jump_if_true => @sizeOf(ops.OpsEqzJump),

        .f32_eq_jump_if_true,
        .f32_ne_jump_if_true,
        .f32_lt_jump_if_true,
        .f32_gt_jump_if_true,
        .f32_le_jump_if_true,
        .f32_ge_jump_if_true,
        .f64_eq_jump_if_true,
        .f64_ne_jump_if_true,
        .f64_lt_jump_if_true,
        .f64_gt_jump_if_true,
        .f64_le_jump_if_true,
        .f64_ge_jump_if_true,
        => @sizeOf(ops.OpsCompareJump),

        .i32_add_to_local,
        .i32_sub_to_local,
        .i32_mul_to_local,
        .i32_and_to_local,
        .i32_or_to_local,
        .i32_xor_to_local,
        .i32_shl_to_local,
        .i32_shr_s_to_local,
        .i32_shr_u_to_local,
        => @sizeOf(ops.OpsBinopToLocal),

        .i64_add_to_local,
        .i64_sub_to_local,
        .i64_mul_to_local,
        .i64_and_to_local,
        .i64_or_to_local,
        .i64_xor_to_local,
        .i64_shl_to_local,
        .i64_shr_s_to_local,
        .i64_shr_u_to_local,
        => @sizeOf(ops.OpsBinopToLocal),

        .f32_add_to_local,
        .f32_sub_to_local,
        .f32_mul_to_local,
        .f32_div_to_local,
        .f64_add_to_local,
        .f64_sub_to_local,
        .f64_mul_to_local,
        .f64_div_to_local,
        => @sizeOf(ops.OpsBinopToLocal),

        .i32_add_tee_local,
        .i32_sub_tee_local,
        .i32_mul_tee_local,
        .i32_and_tee_local,
        .i32_or_tee_local,
        .i32_xor_tee_local,
        .i32_shl_tee_local,
        .i32_shr_s_tee_local,
        .i32_shr_u_tee_local,
        => @sizeOf(ops.OpsBinopTeeLocal),

        .i64_add_tee_local,
        .i64_sub_tee_local,
        .i64_mul_tee_local,
        .i64_and_tee_local,
        .i64_or_tee_local,
        .i64_xor_tee_local,
        .i64_shl_tee_local,
        .i64_shr_s_tee_local,
        .i64_shr_u_tee_local,
        => @sizeOf(ops.OpsBinopTeeLocal),

        .f32_add_tee_local,
        .f32_sub_tee_local,
        .f32_mul_tee_local,
        .f32_div_tee_local,
        .f64_add_tee_local,
        .f64_sub_tee_local,
        .f64_mul_tee_local,
        .f64_div_tee_local,
        => @sizeOf(ops.OpsBinopTeeLocal),

        .i32_eq_to_local,
        .i32_ne_to_local,
        .i32_lt_s_to_local,
        .i32_lt_u_to_local,
        .i32_gt_s_to_local,
        .i32_gt_u_to_local,
        .i32_le_s_to_local,
        .i32_le_u_to_local,
        .i32_ge_s_to_local,
        .i32_ge_u_to_local,
        .i64_eq_to_local,
        .i64_ne_to_local,
        .i64_lt_s_to_local,
        .i64_lt_u_to_local,
        .i64_gt_s_to_local,
        .i64_gt_u_to_local,
        .i64_le_s_to_local,
        .i64_le_u_to_local,
        .i64_ge_s_to_local,
        .i64_ge_u_to_local,
        => @sizeOf(ops.OpsCmpToLocal),

        .f32_eq_to_local,
        .f32_ne_to_local,
        .f32_lt_to_local,
        .f32_gt_to_local,
        .f32_le_to_local,
        .f32_ge_to_local,
        .f64_eq_to_local,
        .f64_ne_to_local,
        .f64_lt_to_local,
        .f64_gt_to_local,
        .f64_le_to_local,
        .f64_ge_to_local,
        => @sizeOf(ops.OpsCmpToLocal),

        .i32_add_imm_to_local,
        .i32_sub_imm_to_local,
        .i32_mul_imm_to_local,
        .i32_and_imm_to_local,
        .i32_or_imm_to_local,
        .i32_xor_imm_to_local,
        .i32_shl_imm_to_local,
        .i32_shr_s_imm_to_local,
        .i32_shr_u_imm_to_local,
        => @sizeOf(ops.OpsBinopImmToLocal),

        .i64_add_imm_to_local,
        .i64_sub_imm_to_local,
        .i64_mul_imm_to_local,
        .i64_and_imm_to_local,
        .i64_or_imm_to_local,
        .i64_xor_imm_to_local,
        .i64_shl_imm_to_local,
        .i64_shr_s_imm_to_local,
        .i64_shr_u_imm_to_local,
        => @sizeOf(ops.OpsBinopImmToLocal64),

        .f32_add_imm_to_local,
        .f32_sub_imm_to_local,
        .f32_mul_imm_to_local,
        .f32_div_imm_to_local,
        => @sizeOf(ops.OpsBinopImmToLocalF32),

        .f64_add_imm_to_local,
        .f64_sub_imm_to_local,
        .f64_mul_imm_to_local,
        .f64_div_imm_to_local,
        => @sizeOf(ops.OpsBinopImmToLocalF64),

        .i32_add_local_inplace,
        .i32_sub_local_inplace,
        .i32_mul_local_inplace,
        .i32_and_local_inplace,
        .i32_or_local_inplace,
        .i32_xor_local_inplace,
        .i32_shl_local_inplace,
        .i32_shr_s_local_inplace,
        .i32_shr_u_local_inplace,
        => @sizeOf(ops.OpsLocalInplace),

        .i64_add_local_inplace,
        .i64_sub_local_inplace,
        .i64_mul_local_inplace,
        .i64_and_local_inplace,
        .i64_or_local_inplace,
        .i64_xor_local_inplace,
        .i64_shl_local_inplace,
        .i64_shr_s_local_inplace,
        .i64_shr_u_local_inplace,
        => @sizeOf(ops.OpsLocalInplace64),

        .f32_add_local_inplace,
        .f32_sub_local_inplace,
        .f32_mul_local_inplace,
        .f32_div_local_inplace,
        => @sizeOf(ops.OpsLocalInplaceF32),

        .f64_add_local_inplace,
        .f64_sub_local_inplace,
        .f64_mul_local_inplace,
        .f64_div_local_inplace,
        => @sizeOf(ops.OpsLocalInplaceF64),

        .i32_const_to_local,
        => @sizeOf(ops.OpsConstToLocal32),

        .i64_const_to_local,
        => @sizeOf(ops.OpsConstToLocal64),

        .i32_imm_to_local,
        => @sizeOf(ops.OpsImm32ToLocal),

        .i64_imm_to_local,
        => @sizeOf(ops.OpsImm64ToLocal),

        .global_get_to_local,
        => @sizeOf(ops.OpsGlobalGetToLocal),

        .i32_load_to_local,
        .i64_load_to_local,
        => @sizeOf(ops.OpsLoadToLocal),

        .i32_eq_imm_jump_if_false,
        .i32_ne_imm_jump_if_false,
        .i32_lt_s_imm_jump_if_false,
        .i32_lt_u_imm_jump_if_false,
        .i32_gt_s_imm_jump_if_false,
        .i32_gt_u_imm_jump_if_false,
        .i32_le_s_imm_jump_if_false,
        .i32_le_u_imm_jump_if_false,
        .i32_ge_s_imm_jump_if_false,
        .i32_ge_u_imm_jump_if_false,
        => @sizeOf(ops.OpsCompareImmJump),

        .i64_eq_imm_jump_if_false,
        .i64_ne_imm_jump_if_false,
        .i64_lt_s_imm_jump_if_false,
        .i64_lt_u_imm_jump_if_false,
        .i64_gt_s_imm_jump_if_false,
        .i64_gt_u_imm_jump_if_false,
        .i64_le_s_imm_jump_if_false,
        .i64_le_u_imm_jump_if_false,
        .i64_ge_s_imm_jump_if_false,
        .i64_ge_u_imm_jump_if_false,
        => @sizeOf(ops.OpsCompareImmJump64),

        .f32_eq_imm_jump_if_false,
        .f32_ne_imm_jump_if_false,
        .f32_lt_imm_jump_if_false,
        .f32_gt_imm_jump_if_false,
        .f32_le_imm_jump_if_false,
        .f32_ge_imm_jump_if_false,
        .f64_eq_imm_jump_if_false,
        .f64_ne_imm_jump_if_false,
        .f64_lt_imm_jump_if_false,
        .f64_gt_imm_jump_if_false,
        .f64_le_imm_jump_if_false,
        .f64_ge_imm_jump_if_false,
        => @sizeOf(ops.OpsCompareImmJumpF64),

        .i32_eq_imm_jump_if_true,
        .i32_ne_imm_jump_if_true,
        .i32_lt_s_imm_jump_if_true,
        .i32_lt_u_imm_jump_if_true,
        .i32_gt_s_imm_jump_if_true,
        .i32_gt_u_imm_jump_if_true,
        .i32_le_s_imm_jump_if_true,
        .i32_le_u_imm_jump_if_true,
        .i32_ge_s_imm_jump_if_true,
        .i32_ge_u_imm_jump_if_true,
        => @sizeOf(ops.OpsCompareImmJump),

        .i64_eq_imm_jump_if_true,
        .i64_ne_imm_jump_if_true,
        .i64_lt_s_imm_jump_if_true,
        .i64_lt_u_imm_jump_if_true,
        .i64_gt_s_imm_jump_if_true,
        .i64_gt_u_imm_jump_if_true,
        .i64_le_s_imm_jump_if_true,
        .i64_le_u_imm_jump_if_true,
        .i64_ge_s_imm_jump_if_true,
        .i64_ge_u_imm_jump_if_true,
        => @sizeOf(ops.OpsCompareImmJump64),

        .f32_eq_imm_jump_if_true,
        .f32_ne_imm_jump_if_true,
        .f32_lt_imm_jump_if_true,
        .f32_gt_imm_jump_if_true,
        .f32_le_imm_jump_if_true,
        .f32_ge_imm_jump_if_true,
        .f64_eq_imm_jump_if_true,
        .f64_ne_imm_jump_if_true,
        .f64_lt_imm_jump_if_true,
        .f64_gt_imm_jump_if_true,
        .f64_le_imm_jump_if_true,
        .f64_ge_imm_jump_if_true,
        => @sizeOf(ops.OpsCompareImmJumpF64),

        .i32_load,
        .i32_load8_s,
        .i32_load8_u,
        .i32_load16_s,
        .i32_load16_u,
        .i64_load,
        .i64_load8_s,
        .i64_load8_u,
        .i64_load16_s,
        .i64_load16_u,
        .i64_load32_s,
        .i64_load32_u,
        .f32_load,
        .f64_load,
        => @sizeOf(ops.OpsLoad),

        .i32_store,
        .i32_store8,
        .i32_store16,
        .i64_store,
        .i64_store8,
        .i64_store16,
        .i64_store32,
        .f32_store,
        .f64_store,
        => @sizeOf(ops.OpsStore),

        .memory_size => @sizeOf(ops.OpsMemorySize),
        .memory_grow => @sizeOf(ops.OpsMemoryGrow),
        .memory_init => @sizeOf(ops.OpsMemoryInit),
        .data_drop => @sizeOf(ops.OpsDataDrop),
        .memory_copy => @sizeOf(ops.OpsMemoryCopy),
        .memory_fill => @sizeOf(ops.OpsMemoryFill),

        .call => |inst| @sizeOf(ops.OpsCall) + @as(usize, inst.args_len) * @sizeOf(Slot),
        .call_to_local => |inst| @sizeOf(ops.OpsCallToLocal) + @as(usize, inst.args_len) * @sizeOf(Slot),
        .call_leaf => |inst| @sizeOf(ops.OpsCallLeaf) + @as(usize, inst.args_len) * @sizeOf(Slot),
        .call_indirect => |inst| @sizeOf(ops.OpsCallIndirect) + @as(usize, inst.args_len) * @sizeOf(Slot),
        .return_call => |inst| @sizeOf(ops.OpsReturnCall) + @as(usize, inst.args_len) * @sizeOf(Slot),
        .return_call_indirect => |inst| @sizeOf(ops.OpsReturnCallIndirect) + @as(usize, inst.args_len) * @sizeOf(Slot),
        .call_ref => |inst| @sizeOf(ops.OpsCallRef) + @as(usize, inst.args_len) * @sizeOf(Slot),
        .return_call_ref => |inst| @sizeOf(ops.OpsReturnCallRef) + @as(usize, inst.args_len) * @sizeOf(Slot),

        .atomic_load => @sizeOf(ops.OpsAtomicLoad),
        .atomic_store => @sizeOf(ops.OpsAtomicStore),
        .atomic_rmw => @sizeOf(ops.OpsAtomicRmw),
        .atomic_cmpxchg => @sizeOf(ops.OpsAtomicCmpxchg),
        .atomic_fence => @sizeOf(ops.OpsNone),
        .atomic_notify => @sizeOf(ops.OpsAtomicNotify),
        .atomic_wait32 => @sizeOf(ops.OpsAtomicWait32),
        .atomic_wait64 => @sizeOf(ops.OpsAtomicWait64),

        .table_get => @sizeOf(ops.OpsTableGet),
        .table_set => @sizeOf(ops.OpsTableSet),
        .table_size => @sizeOf(ops.OpsTableSize),
        .table_grow => @sizeOf(ops.OpsTableGrow),
        .table_fill => @sizeOf(ops.OpsTableFill),
        .table_copy => @sizeOf(ops.OpsTableCopy),
        .table_init => @sizeOf(ops.OpsTableInit),
        .elem_drop => @sizeOf(ops.OpsElemDrop),

        .struct_new => |inst| @sizeOf(ops.OpsStructNew) + @as(usize, inst.args_len) * @sizeOf(Slot),
        .struct_new_default => @sizeOf(ops.OpsStructNewDefault),
        .struct_get, .struct_get_s, .struct_get_u => @sizeOf(ops.OpsStructGet),
        .struct_set => @sizeOf(ops.OpsStructSet),

        .array_new => @sizeOf(ops.OpsArrayNew),
        .array_new_default => @sizeOf(ops.OpsArrayNewDefault),
        .array_new_fixed => |inst| @sizeOf(ops.OpsArrayNewFixed) + @as(usize, inst.args_len) * @sizeOf(Slot),
        .array_new_data => @sizeOf(ops.OpsArrayNewData),
        .array_new_elem => @sizeOf(ops.OpsArrayNewElem),
        .array_get, .array_get_s, .array_get_u => @sizeOf(ops.OpsArrayGet),
        .array_set => @sizeOf(ops.OpsArraySet),
        .array_len => @sizeOf(ops.OpsArrayLen),
        .array_fill => @sizeOf(ops.OpsArrayFill),
        .array_copy => @sizeOf(ops.OpsArrayCopy),
        .array_init_data => @sizeOf(ops.OpsArrayInitData),
        .array_init_elem => @sizeOf(ops.OpsArrayInitElem),

        .ref_i31 => @sizeOf(ops.OpsRefI31),
        .i31_get_s, .i31_get_u => @sizeOf(ops.OpsI31Get),

        .ref_test, .ref_cast => @sizeOf(ops.OpsRefTest),
        .ref_as_non_null => @sizeOf(ops.OpsRefAsNonNull),
        .br_on_null, .br_on_non_null => @sizeOf(ops.OpsBrOnNull),
        .br_on_cast, .br_on_cast_fail => @sizeOf(ops.OpsBrOnCast),

        .any_convert_extern, .extern_convert_any => @sizeOf(ops.OpsConvertRef),

        .throw => |inst| @sizeOf(ops.OpsThrow) + @as(usize, inst.args_len) * @sizeOf(Slot),
        .throw_ref => @sizeOf(ops.OpsThrowRef),
        .try_table_enter => @sizeOf(ops.OpsTryTableEnter),
        .try_table_leave => @sizeOf(ops.OpsTryTableLeave),

        .simd_unary, .simd_compare => @sizeOf(ops.OpsSimdUnary),
        .simd_binary, .simd_shift_scalar => @sizeOf(ops.OpsSimdBinary),
        .simd_ternary => @sizeOf(ops.OpsSimdTernary),
        .simd_extract_lane => @sizeOf(ops.OpsSimdExtractLane),
        .simd_replace_lane => @sizeOf(ops.OpsSimdReplaceLane),
        .simd_shuffle => @sizeOf(ops.OpsSimdShuffle),
        .simd_load => @sizeOf(ops.OpsSimdLoad),
        .simd_store => @sizeOf(ops.OpsSimdStore),
    };
    return HANDLER_SIZE + ops_size;
}
