// Auto-generated by scripts/gen_simd_static.py — do not edit.
const std = @import("std");
const helper = @import("../value/helper.zig");
const base = @import("ops.zig");

const V128 = base.V128;
const vecFromV128 = base.vecFromV128;
const v128FromVec = base.v128FromVec;
const vectorMaskToV128 = base.vectorMaskToV128;
const v128FromBytes = base.v128FromBytes;
const readLane = base.readLane;
const writeLane = base.writeLane;
const narrowLane = base.narrowLane;

pub fn f32x4Abs(value: V128) V128 {
    const lanes = vecFromV128(f32, 4, value);
    return v128FromVec(f32, 4, @abs(lanes));
}

pub fn f32x4Add(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f32, 4, lhs);
    const b = vecFromV128(f32, 4, rhs);
    return v128FromVec(f32, 4, a + b);
}

pub fn f32x4Ceil(value: V128) V128 {
    const lanes = vecFromV128(f32, 4, value);
    return v128FromVec(f32, 4, @ceil(lanes));
}

pub fn f32x4ConvertI32x4S(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        writeLane(f32, &out, @intCast(i), @floatFromInt(readLane(i32, value.bytes, @intCast(i))));
    }
    return v128FromBytes(out);
}

pub fn f32x4ConvertI32x4U(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        writeLane(f32, &out, @intCast(i), @floatFromInt(readLane(u32, value.bytes, @intCast(i))));
    }
    return v128FromBytes(out);
}

pub fn f32x4Div(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f32, 4, lhs);
    const b = vecFromV128(f32, 4, rhs);
    return v128FromVec(f32, 4, a / b);
}

pub fn f32x4Eq(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f32, 4, lhs);
    const b = vecFromV128(f32, 4, rhs);
    const mask = a == b;
    return vectorMaskToV128(f32, 4, mask);
}

pub fn f32x4Floor(value: V128) V128 {
    const lanes = vecFromV128(f32, 4, value);
    return v128FromVec(f32, 4, @floor(lanes));
}

pub fn f32x4Ge(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f32, 4, lhs);
    const b = vecFromV128(f32, 4, rhs);
    const mask = a >= b;
    return vectorMaskToV128(f32, 4, mask);
}

pub fn f32x4Gt(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f32, 4, lhs);
    const b = vecFromV128(f32, 4, rhs);
    const mask = a > b;
    return vectorMaskToV128(f32, 4, mask);
}

pub fn f32x4Le(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f32, 4, lhs);
    const b = vecFromV128(f32, 4, rhs);
    const mask = a <= b;
    return vectorMaskToV128(f32, 4, mask);
}

pub fn f32x4Lt(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f32, 4, lhs);
    const b = vecFromV128(f32, 4, rhs);
    const mask = a < b;
    return vectorMaskToV128(f32, 4, mask);
}

pub fn f32x4Max(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const lane_a = readLane(f32, lhs.bytes, @intCast(i));
        const lane_b = readLane(f32, rhs.bytes, @intCast(i));
        const result: f32 = helper.max(lane_a, lane_b);
        writeLane(f32, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn f32x4Min(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const lane_a = readLane(f32, lhs.bytes, @intCast(i));
        const lane_b = readLane(f32, rhs.bytes, @intCast(i));
        const result: f32 = helper.min(lane_a, lane_b);
        writeLane(f32, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn f32x4Mul(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f32, 4, lhs);
    const b = vecFromV128(f32, 4, rhs);
    return v128FromVec(f32, 4, a * b);
}

pub fn f32x4Ne(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f32, 4, lhs);
    const b = vecFromV128(f32, 4, rhs);
    const mask = a != b;
    return vectorMaskToV128(f32, 4, mask);
}

pub fn f32x4Nearest(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const lane = readLane(f32, value.bytes, @intCast(i));
        writeLane(f32, &out, @intCast(i), helper.nearest(lane));
    }
    return v128FromBytes(out);
}

pub fn f32x4Neg(value: V128) V128 {
    const lanes = vecFromV128(f32, 4, value);
    return v128FromVec(f32, 4, -lanes);
}

pub fn f32x4Pmax(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f32, 4, lhs);
    const b = vecFromV128(f32, 4, rhs);
    return v128FromVec(f32, 4, @select(f32, a < b, b, a));
}

pub fn f32x4Pmin(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f32, 4, lhs);
    const b = vecFromV128(f32, 4, rhs);
    return v128FromVec(f32, 4, @select(f32, b < a, b, a));
}

pub fn f32x4RelaxedMadd(first: V128, second: V128, third: V128) V128 {
    const a = vecFromV128(f32, 4, first);
    const b = vecFromV128(f32, 4, second);
    const c = vecFromV128(f32, 4, third);
    return v128FromVec(f32, 4, @mulAdd(F32x4, a, b, c));
}

pub fn f32x4RelaxedMax(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const lane_a = readLane(f32, lhs.bytes, @intCast(i));
        const lane_b = readLane(f32, rhs.bytes, @intCast(i));
        const result: f32 = helper.max(lane_a, lane_b);
        writeLane(f32, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn f32x4RelaxedMin(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const lane_a = readLane(f32, lhs.bytes, @intCast(i));
        const lane_b = readLane(f32, rhs.bytes, @intCast(i));
        const result: f32 = helper.min(lane_a, lane_b);
        writeLane(f32, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn f32x4RelaxedNmadd(first: V128, second: V128, third: V128) V128 {
    var a = vecFromV128(f32, 4, first);
    const b = vecFromV128(f32, 4, second);
    const c = vecFromV128(f32, 4, third);
    a = -a;
    return v128FromVec(f32, 4, @mulAdd(F32x4, a, b, c));
}

pub fn f32x4Splat(value: f32) V128 {
    return v128FromVec(f32, 4, @as(F32x4, @splat(value)));
}

pub fn f32x4Sqrt(value: V128) V128 {
    const lanes = vecFromV128(f32, 4, value);
    return v128FromVec(f32, 4, @sqrt(lanes));
}

pub fn f32x4Sub(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f32, 4, lhs);
    const b = vecFromV128(f32, 4, rhs);
    return v128FromVec(f32, 4, a - b);
}

pub fn f32x4Trunc(value: V128) V128 {
    const lanes = vecFromV128(f32, 4, value);
    return v128FromVec(f32, 4, @trunc(lanes));
}

pub fn f64x2Abs(value: V128) V128 {
    const lanes = vecFromV128(f64, 2, value);
    return v128FromVec(f64, 2, @abs(lanes));
}

pub fn f64x2Add(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f64, 2, lhs);
    const b = vecFromV128(f64, 2, rhs);
    return v128FromVec(f64, 2, a + b);
}

pub fn f64x2Ceil(value: V128) V128 {
    const lanes = vecFromV128(f64, 2, value);
    return v128FromVec(f64, 2, @ceil(lanes));
}

pub fn f64x2ConvertLowI32x4S(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        writeLane(f64, &out, @intCast(i), @floatFromInt(readLane(i32, value.bytes, @intCast(i))));
    }
    return v128FromBytes(out);
}

pub fn f64x2ConvertLowI32x4U(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        writeLane(f64, &out, @intCast(i), @floatFromInt(readLane(u32, value.bytes, @intCast(i))));
    }
    return v128FromBytes(out);
}

pub fn f64x2Div(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f64, 2, lhs);
    const b = vecFromV128(f64, 2, rhs);
    return v128FromVec(f64, 2, a / b);
}

pub fn f64x2Eq(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f64, 2, lhs);
    const b = vecFromV128(f64, 2, rhs);
    const mask = a == b;
    return vectorMaskToV128(f64, 2, mask);
}

pub fn f64x2Floor(value: V128) V128 {
    const lanes = vecFromV128(f64, 2, value);
    return v128FromVec(f64, 2, @floor(lanes));
}

pub fn f64x2Ge(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f64, 2, lhs);
    const b = vecFromV128(f64, 2, rhs);
    const mask = a >= b;
    return vectorMaskToV128(f64, 2, mask);
}

pub fn f64x2Gt(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f64, 2, lhs);
    const b = vecFromV128(f64, 2, rhs);
    const mask = a > b;
    return vectorMaskToV128(f64, 2, mask);
}

pub fn f64x2Le(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f64, 2, lhs);
    const b = vecFromV128(f64, 2, rhs);
    const mask = a <= b;
    return vectorMaskToV128(f64, 2, mask);
}

pub fn f64x2Lt(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f64, 2, lhs);
    const b = vecFromV128(f64, 2, rhs);
    const mask = a < b;
    return vectorMaskToV128(f64, 2, mask);
}

pub fn f64x2Max(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const lane_a = readLane(f64, lhs.bytes, @intCast(i));
        const lane_b = readLane(f64, rhs.bytes, @intCast(i));
        const result: f64 = helper.max(lane_a, lane_b);
        writeLane(f64, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn f64x2Min(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const lane_a = readLane(f64, lhs.bytes, @intCast(i));
        const lane_b = readLane(f64, rhs.bytes, @intCast(i));
        const result: f64 = helper.min(lane_a, lane_b);
        writeLane(f64, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn f64x2Mul(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f64, 2, lhs);
    const b = vecFromV128(f64, 2, rhs);
    return v128FromVec(f64, 2, a * b);
}

pub fn f64x2Ne(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f64, 2, lhs);
    const b = vecFromV128(f64, 2, rhs);
    const mask = a != b;
    return vectorMaskToV128(f64, 2, mask);
}

pub fn f64x2Nearest(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const lane = readLane(f64, value.bytes, @intCast(i));
        writeLane(f64, &out, @intCast(i), helper.nearest(lane));
    }
    return v128FromBytes(out);
}

pub fn f64x2Neg(value: V128) V128 {
    const lanes = vecFromV128(f64, 2, value);
    return v128FromVec(f64, 2, -lanes);
}

pub fn f64x2Pmax(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f64, 2, lhs);
    const b = vecFromV128(f64, 2, rhs);
    return v128FromVec(f64, 2, @select(f64, a < b, b, a));
}

pub fn f64x2Pmin(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f64, 2, lhs);
    const b = vecFromV128(f64, 2, rhs);
    return v128FromVec(f64, 2, @select(f64, b < a, b, a));
}

pub fn f64x2RelaxedMadd(first: V128, second: V128, third: V128) V128 {
    const a = vecFromV128(f64, 2, first);
    const b = vecFromV128(f64, 2, second);
    const c = vecFromV128(f64, 2, third);
    return v128FromVec(f64, 2, @mulAdd(F64x2, a, b, c));
}

pub fn f64x2RelaxedMax(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const lane_a = readLane(f64, lhs.bytes, @intCast(i));
        const lane_b = readLane(f64, rhs.bytes, @intCast(i));
        const result: f64 = helper.max(lane_a, lane_b);
        writeLane(f64, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn f64x2RelaxedMin(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const lane_a = readLane(f64, lhs.bytes, @intCast(i));
        const lane_b = readLane(f64, rhs.bytes, @intCast(i));
        const result: f64 = helper.min(lane_a, lane_b);
        writeLane(f64, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn f64x2RelaxedNmadd(first: V128, second: V128, third: V128) V128 {
    var a = vecFromV128(f64, 2, first);
    const b = vecFromV128(f64, 2, second);
    const c = vecFromV128(f64, 2, third);
    a = -a;
    return v128FromVec(f64, 2, @mulAdd(F64x2, a, b, c));
}

pub fn f64x2Splat(value: f64) V128 {
    return v128FromVec(f64, 2, @as(F64x2, @splat(value)));
}

pub fn f64x2Sqrt(value: V128) V128 {
    const lanes = vecFromV128(f64, 2, value);
    return v128FromVec(f64, 2, @sqrt(lanes));
}

pub fn f64x2Sub(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(f64, 2, lhs);
    const b = vecFromV128(f64, 2, rhs);
    return v128FromVec(f64, 2, a - b);
}

pub fn f64x2Trunc(value: V128) V128 {
    const lanes = vecFromV128(f64, 2, value);
    return v128FromVec(f64, 2, @trunc(lanes));
}

pub fn i16x8Abs(value: V128) V128 {
    const lanes = vecFromV128(i16, 8, value);
    const zero: I16x8 = @splat(0);
    const results: I16x8 = @select(i16, lanes < zero, zero -% lanes, lanes);
    return v128FromVec(i16, 8, results);
}

pub fn i16x8Add(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i16, 8, lhs);
    const b = vecFromV128(i16, 8, rhs);
    return v128FromVec(i16, 8, a +% b);
}

pub fn i16x8AddSatS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i16, 8, lhs);
    const b = vecFromV128(i16, 8, rhs);
    return v128FromVec(i16, 8, a +| b);
}

pub fn i16x8AddSatU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u16, 8, lhs);
    const b = vecFromV128(u16, 8, rhs);
    return v128FromVec(u16, 8, a +| b);
}

pub fn i16x8AllTrue(value: V128) bool {
    const lanes = vecFromV128(i16, 8, value);
    const zero: I16x8 = @splat(0);
    return @reduce(.And, lanes != zero);
}

pub fn i16x8AvgrU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u16, 8, lhs);
    const b = vecFromV128(u16, 8, rhs);
    const ShiftT = std.math.Log2Int(u16);
    const shifts: @Vector(8, ShiftT) = @splat(1);
    return v128FromVec(u16, 8, (a | b) - ((a ^ b) >> shifts));
}

pub fn i16x8Bitmask(value: V128) i32 {
    const lanes = vecFromV128(i16, 8, value);
    const zero: I16x8 = @splat(0);
    const sign_bits: @Vector(8, u1) = @bitCast(lanes < zero);
    const MaskInt = std.meta.Int(.unsigned, 8);
    const mask_uint: MaskInt = @bitCast(sign_bits);
    return @as(i32, @intCast(mask_uint));
}

pub fn i16x8Eq(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i16, 8, lhs);
    const b = vecFromV128(i16, 8, rhs);
    const mask = a == b;
    return vectorMaskToV128(i16, 8, mask);
}

pub fn i16x8ExtaddPairwiseI8x16S(value: V128) V128 {
    const PairT = i16;
    const PairVec = @Vector(8, PairT);
    const pairs = vecFromV128(PairT, 8, value);
    const bits = @bitSizeOf(i8);
    const shift_amt: @Vector(8, std.math.Log2Int(PairT)) = @splat(bits);
    if (true) {
        const low: PairVec = (pairs << shift_amt) >> shift_amt;
        const high: PairVec = pairs >> shift_amt;
        return v128FromVec(PairT, 8, low + high);
    } else {
        const mask_val: PairT = (@as(PairT, 1) << @intCast(bits)) - 1;
        const mask: PairVec = @splat(mask_val);
        const low: PairVec = pairs & mask;
        const high: PairVec = pairs >> shift_amt;
        return v128FromVec(PairT, 8, low + high);
    }
}

pub fn i16x8ExtaddPairwiseI8x16U(value: V128) V128 {
    const PairT = i16;
    const PairVec = @Vector(8, PairT);
    const pairs = vecFromV128(PairT, 8, value);
    const bits = @bitSizeOf(i8);
    const shift_amt: @Vector(8, std.math.Log2Int(PairT)) = @splat(bits);
    if (true) {
        const low: PairVec = (pairs << shift_amt) >> shift_amt;
        const high: PairVec = pairs >> shift_amt;
        return v128FromVec(PairT, 8, low + high);
    } else {
        const mask_val: PairT = (@as(PairT, 1) << @intCast(bits)) - 1;
        const mask: PairVec = @splat(mask_val);
        const low: PairVec = pairs & mask;
        const high: PairVec = pairs >> shift_amt;
        return v128FromVec(PairT, 8, low + high);
    }
}

pub fn i16x8ExtendHighI8x16S(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..8) |i| {
        const lane = readLane(i8, value.bytes, @intCast(8 + i));
        const result: i16 = if (true) @as(i16, lane) else @as(i16, @intCast(lane));
        writeLane(i16, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i16x8ExtendHighI8x16U(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..8) |i| {
        const lane = readLane(i8, value.bytes, @intCast(8 + i));
        const result: i16 = if (true) @as(i16, lane) else @as(i16, @intCast(lane));
        writeLane(i16, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i16x8ExtendLowI8x16S(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..8) |i| {
        const lane = readLane(i8, value.bytes, @intCast(0 + i));
        const result: i16 = if (true) @as(i16, lane) else @as(i16, @intCast(lane));
        writeLane(i16, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i16x8ExtendLowI8x16U(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..8) |i| {
        const lane = readLane(i8, value.bytes, @intCast(0 + i));
        const result: i16 = if (true) @as(i16, lane) else @as(i16, @intCast(lane));
        writeLane(i16, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i16x8ExtmulHighI8x16S(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..8) |i| {
        const a = readLane(i8, lhs.bytes, @intCast(8 + i));
        const b = readLane(i8, rhs.bytes, @intCast(8 + i));
        const result: i16 = @as(i16, a) * @as(i16, b);
        writeLane(i16, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i16x8ExtmulHighI8x16U(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..8) |i| {
        const a = readLane(i8, lhs.bytes, @intCast(8 + i));
        const b = readLane(i8, rhs.bytes, @intCast(8 + i));
        const result: i16 = @as(i16, a) * @as(i16, b);
        writeLane(i16, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i16x8ExtmulLowI8x16S(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..8) |i| {
        const a = readLane(i8, lhs.bytes, @intCast(0 + i));
        const b = readLane(i8, rhs.bytes, @intCast(0 + i));
        const result: i16 = @as(i16, a) * @as(i16, b);
        writeLane(i16, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i16x8ExtmulLowI8x16U(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..8) |i| {
        const a = readLane(i8, lhs.bytes, @intCast(0 + i));
        const b = readLane(i8, rhs.bytes, @intCast(0 + i));
        const result: i16 = @as(i16, a) * @as(i16, b);
        writeLane(i16, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i16x8GeS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i16, 8, lhs);
    const b = vecFromV128(i16, 8, rhs);
    const mask = a >= b;
    return vectorMaskToV128(i16, 8, mask);
}

pub fn i16x8GeU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u16, 8, lhs);
    const b = vecFromV128(u16, 8, rhs);
    const mask = a >= b;
    return vectorMaskToV128(u16, 8, mask);
}

pub fn i16x8GtS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i16, 8, lhs);
    const b = vecFromV128(i16, 8, rhs);
    const mask = a > b;
    return vectorMaskToV128(i16, 8, mask);
}

pub fn i16x8GtU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u16, 8, lhs);
    const b = vecFromV128(u16, 8, rhs);
    const mask = a > b;
    return vectorMaskToV128(u16, 8, mask);
}

pub fn i16x8LeS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i16, 8, lhs);
    const b = vecFromV128(i16, 8, rhs);
    const mask = a <= b;
    return vectorMaskToV128(i16, 8, mask);
}

pub fn i16x8LeU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u16, 8, lhs);
    const b = vecFromV128(u16, 8, rhs);
    const mask = a <= b;
    return vectorMaskToV128(u16, 8, mask);
}

pub fn i16x8LtS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i16, 8, lhs);
    const b = vecFromV128(i16, 8, rhs);
    const mask = a < b;
    return vectorMaskToV128(i16, 8, mask);
}

pub fn i16x8LtU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u16, 8, lhs);
    const b = vecFromV128(u16, 8, rhs);
    const mask = a < b;
    return vectorMaskToV128(u16, 8, mask);
}

pub fn i16x8MaxS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i16, 8, lhs);
    const b = vecFromV128(i16, 8, rhs);
    return v128FromVec(i16, 8, @select(i16, a > b, a, b));
}

pub fn i16x8MaxU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u16, 8, lhs);
    const b = vecFromV128(u16, 8, rhs);
    return v128FromVec(u16, 8, @select(u16, a > b, a, b));
}

pub fn i16x8MinS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i16, 8, lhs);
    const b = vecFromV128(i16, 8, rhs);
    return v128FromVec(i16, 8, @select(i16, a < b, a, b));
}

pub fn i16x8MinU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u16, 8, lhs);
    const b = vecFromV128(u16, 8, rhs);
    return v128FromVec(u16, 8, @select(u16, a < b, a, b));
}

pub fn i16x8Mul(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i16, 8, lhs);
    const b = vecFromV128(i16, 8, rhs);
    return v128FromVec(i16, 8, a *% b);
}

pub fn i16x8NarrowI32x4S(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        writeLane(i16, &out, @intCast(i), narrowLane(i32, i16, readLane(i32, lhs.bytes, @intCast(i)), true));
        writeLane(i16, &out, @intCast(4 + i), narrowLane(i32, i16, readLane(i32, rhs.bytes, @intCast(i)), true));
    }
    return v128FromBytes(out);
}

pub fn i16x8NarrowI32x4U(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        writeLane(i16, &out, @intCast(i), narrowLane(i32, i16, readLane(i32, lhs.bytes, @intCast(i)), true));
        writeLane(i16, &out, @intCast(4 + i), narrowLane(i32, i16, readLane(i32, rhs.bytes, @intCast(i)), true));
    }
    return v128FromBytes(out);
}

pub fn i16x8Ne(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i16, 8, lhs);
    const b = vecFromV128(i16, 8, rhs);
    const mask = a != b;
    return vectorMaskToV128(i16, 8, mask);
}

pub fn i16x8Neg(value: V128) V128 {
    const lanes = vecFromV128(i16, 8, value);
    const zero: I16x8 = @splat(0);
    return v128FromVec(i16, 8, zero -% lanes);
}

pub fn i16x8Shl(value: V128, amount: u32) V128 {
    const ShiftT = std.math.Log2Int(i16);
    const shift: ShiftT = @intCast(amount % @bitSizeOf(i16));
    const lanes = vecFromV128(i16, 8, value);
    const shifts: @Vector(8, ShiftT) = @splat(shift);
    return v128FromVec(i16, 8, lanes << shifts);
}

pub fn i16x8ShrS(value: V128, amount: u32) V128 {
    const ShiftT = std.math.Log2Int(i16);
    const shift: ShiftT = @intCast(amount % @bitSizeOf(i16));
    const lanes = vecFromV128(i16, 8, value);
    const shifts: @Vector(8, ShiftT) = @splat(shift);
    return v128FromVec(i16, 8, lanes >> shifts);
}

pub fn i16x8ShrU(value: V128, amount: u32) V128 {
    const ShiftT = std.math.Log2Int(u16);
    const shift: ShiftT = @intCast(amount % @bitSizeOf(u16));
    const lanes = vecFromV128(u16, 8, value);
    const shifts: @Vector(8, ShiftT) = @splat(shift);
    return v128FromVec(u16, 8, lanes >> shifts);
}

pub fn i16x8Splat(value: i16) V128 {
    return v128FromVec(i16, 8, @as(I16x8, @splat(value)));
}

pub fn i16x8Sub(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i16, 8, lhs);
    const b = vecFromV128(i16, 8, rhs);
    return v128FromVec(i16, 8, a -% b);
}

pub fn i16x8SubSatS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i16, 8, lhs);
    const b = vecFromV128(i16, 8, rhs);
    return v128FromVec(i16, 8, a -| b);
}

pub fn i16x8SubSatU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u16, 8, lhs);
    const b = vecFromV128(u16, 8, rhs);
    return v128FromVec(u16, 8, a -| b);
}

pub fn i32x4Abs(value: V128) V128 {
    const lanes = vecFromV128(i32, 4, value);
    const zero: I32x4 = @splat(0);
    const results: I32x4 = @select(i32, lanes < zero, zero -% lanes, lanes);
    return v128FromVec(i32, 4, results);
}

pub fn i32x4Add(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i32, 4, lhs);
    const b = vecFromV128(i32, 4, rhs);
    return v128FromVec(i32, 4, a +% b);
}

pub fn i32x4AllTrue(value: V128) bool {
    const lanes = vecFromV128(i32, 4, value);
    const zero: I32x4 = @splat(0);
    return @reduce(.And, lanes != zero);
}

pub fn i32x4Bitmask(value: V128) i32 {
    const lanes = vecFromV128(i32, 4, value);
    const zero: I32x4 = @splat(0);
    const sign_bits: @Vector(4, u1) = @bitCast(lanes < zero);
    const MaskInt = std.meta.Int(.unsigned, 4);
    const mask_uint: MaskInt = @bitCast(sign_bits);
    return @as(i32, @intCast(mask_uint));
}

pub fn i32x4Eq(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i32, 4, lhs);
    const b = vecFromV128(i32, 4, rhs);
    const mask = a == b;
    return vectorMaskToV128(i32, 4, mask);
}

pub fn i32x4ExtaddPairwiseI16x8S(value: V128) V128 {
    const PairT = i32;
    const PairVec = @Vector(4, PairT);
    const pairs = vecFromV128(PairT, 4, value);
    const bits = @bitSizeOf(i16);
    const shift_amt: @Vector(4, std.math.Log2Int(PairT)) = @splat(bits);
    if (true) {
        const low: PairVec = (pairs << shift_amt) >> shift_amt;
        const high: PairVec = pairs >> shift_amt;
        return v128FromVec(PairT, 4, low + high);
    } else {
        const mask_val: PairT = (@as(PairT, 1) << @intCast(bits)) - 1;
        const mask: PairVec = @splat(mask_val);
        const low: PairVec = pairs & mask;
        const high: PairVec = pairs >> shift_amt;
        return v128FromVec(PairT, 4, low + high);
    }
}

pub fn i32x4ExtaddPairwiseI16x8U(value: V128) V128 {
    const PairT = i32;
    const PairVec = @Vector(4, PairT);
    const pairs = vecFromV128(PairT, 4, value);
    const bits = @bitSizeOf(i16);
    const shift_amt: @Vector(4, std.math.Log2Int(PairT)) = @splat(bits);
    if (true) {
        const low: PairVec = (pairs << shift_amt) >> shift_amt;
        const high: PairVec = pairs >> shift_amt;
        return v128FromVec(PairT, 4, low + high);
    } else {
        const mask_val: PairT = (@as(PairT, 1) << @intCast(bits)) - 1;
        const mask: PairVec = @splat(mask_val);
        const low: PairVec = pairs & mask;
        const high: PairVec = pairs >> shift_amt;
        return v128FromVec(PairT, 4, low + high);
    }
}

pub fn i32x4ExtendHighI16x8S(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const lane = readLane(i16, value.bytes, @intCast(4 + i));
        const result: i32 = if (true) @as(i32, lane) else @as(i32, @intCast(lane));
        writeLane(i32, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i32x4ExtendHighI16x8U(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const lane = readLane(i16, value.bytes, @intCast(4 + i));
        const result: i32 = if (true) @as(i32, lane) else @as(i32, @intCast(lane));
        writeLane(i32, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i32x4ExtendLowI16x8S(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const lane = readLane(i16, value.bytes, @intCast(0 + i));
        const result: i32 = if (true) @as(i32, lane) else @as(i32, @intCast(lane));
        writeLane(i32, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i32x4ExtendLowI16x8U(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const lane = readLane(i16, value.bytes, @intCast(0 + i));
        const result: i32 = if (true) @as(i32, lane) else @as(i32, @intCast(lane));
        writeLane(i32, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i32x4ExtmulHighI16x8S(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const a = readLane(i16, lhs.bytes, @intCast(4 + i));
        const b = readLane(i16, rhs.bytes, @intCast(4 + i));
        const result: i32 = @as(i32, a) * @as(i32, b);
        writeLane(i32, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i32x4ExtmulHighI16x8U(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const a = readLane(i16, lhs.bytes, @intCast(4 + i));
        const b = readLane(i16, rhs.bytes, @intCast(4 + i));
        const result: i32 = @as(i32, a) * @as(i32, b);
        writeLane(i32, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i32x4ExtmulLowI16x8S(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const a = readLane(i16, lhs.bytes, @intCast(0 + i));
        const b = readLane(i16, rhs.bytes, @intCast(0 + i));
        const result: i32 = @as(i32, a) * @as(i32, b);
        writeLane(i32, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i32x4ExtmulLowI16x8U(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const a = readLane(i16, lhs.bytes, @intCast(0 + i));
        const b = readLane(i16, rhs.bytes, @intCast(0 + i));
        const result: i32 = @as(i32, a) * @as(i32, b);
        writeLane(i32, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i32x4GeS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i32, 4, lhs);
    const b = vecFromV128(i32, 4, rhs);
    const mask = a >= b;
    return vectorMaskToV128(i32, 4, mask);
}

pub fn i32x4GeU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u32, 4, lhs);
    const b = vecFromV128(u32, 4, rhs);
    const mask = a >= b;
    return vectorMaskToV128(u32, 4, mask);
}

pub fn i32x4GtS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i32, 4, lhs);
    const b = vecFromV128(i32, 4, rhs);
    const mask = a > b;
    return vectorMaskToV128(i32, 4, mask);
}

pub fn i32x4GtU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u32, 4, lhs);
    const b = vecFromV128(u32, 4, rhs);
    const mask = a > b;
    return vectorMaskToV128(u32, 4, mask);
}

pub fn i32x4LeS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i32, 4, lhs);
    const b = vecFromV128(i32, 4, rhs);
    const mask = a <= b;
    return vectorMaskToV128(i32, 4, mask);
}

pub fn i32x4LeU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u32, 4, lhs);
    const b = vecFromV128(u32, 4, rhs);
    const mask = a <= b;
    return vectorMaskToV128(u32, 4, mask);
}

pub fn i32x4LtS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i32, 4, lhs);
    const b = vecFromV128(i32, 4, rhs);
    const mask = a < b;
    return vectorMaskToV128(i32, 4, mask);
}

pub fn i32x4LtU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u32, 4, lhs);
    const b = vecFromV128(u32, 4, rhs);
    const mask = a < b;
    return vectorMaskToV128(u32, 4, mask);
}

pub fn i32x4MaxS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i32, 4, lhs);
    const b = vecFromV128(i32, 4, rhs);
    return v128FromVec(i32, 4, @select(i32, a > b, a, b));
}

pub fn i32x4MaxU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u32, 4, lhs);
    const b = vecFromV128(u32, 4, rhs);
    return v128FromVec(u32, 4, @select(u32, a > b, a, b));
}

pub fn i32x4MinS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i32, 4, lhs);
    const b = vecFromV128(i32, 4, rhs);
    return v128FromVec(i32, 4, @select(i32, a < b, a, b));
}

pub fn i32x4MinU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u32, 4, lhs);
    const b = vecFromV128(u32, 4, rhs);
    return v128FromVec(u32, 4, @select(u32, a < b, a, b));
}

pub fn i32x4Mul(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i32, 4, lhs);
    const b = vecFromV128(i32, 4, rhs);
    return v128FromVec(i32, 4, a *% b);
}

pub fn i32x4Ne(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i32, 4, lhs);
    const b = vecFromV128(i32, 4, rhs);
    const mask = a != b;
    return vectorMaskToV128(i32, 4, mask);
}

pub fn i32x4Neg(value: V128) V128 {
    const lanes = vecFromV128(i32, 4, value);
    const zero: I32x4 = @splat(0);
    return v128FromVec(i32, 4, zero -% lanes);
}

pub fn i32x4RelaxedTruncF32x4S(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const lane = readLane(f32, value.bytes, @intCast(i));
        writeLane(i32, &out, @intCast(i), helper.truncateSaturateInto(i32, lane));
    }
    return v128FromBytes(out);
}

pub fn i32x4RelaxedTruncF32x4U(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const lane = readLane(f32, value.bytes, @intCast(i));
        const bits = helper.truncateSaturateInto(u32, lane);
            writeLane(i32, &out, @intCast(i), @bitCast(bits));
    }
    return v128FromBytes(out);
}

pub fn i32x4RelaxedTruncF64x2SZero(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const lane = readLane(f64, value.bytes, @intCast(i));
        writeLane(i32, &out, @intCast(i), helper.truncateSaturateInto(i32, lane));
    }
    return v128FromBytes(out);
}

pub fn i32x4RelaxedTruncF64x2UZero(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const lane = readLane(f64, value.bytes, @intCast(i));
        const bits = helper.truncateSaturateInto(u32, lane);
            writeLane(i32, &out, @intCast(i), @bitCast(bits));
    }
    return v128FromBytes(out);
}

pub fn i32x4Shl(value: V128, amount: u32) V128 {
    const ShiftT = std.math.Log2Int(i32);
    const shift: ShiftT = @intCast(amount % @bitSizeOf(i32));
    const lanes = vecFromV128(i32, 4, value);
    const shifts: @Vector(4, ShiftT) = @splat(shift);
    return v128FromVec(i32, 4, lanes << shifts);
}

pub fn i32x4ShrS(value: V128, amount: u32) V128 {
    const ShiftT = std.math.Log2Int(i32);
    const shift: ShiftT = @intCast(amount % @bitSizeOf(i32));
    const lanes = vecFromV128(i32, 4, value);
    const shifts: @Vector(4, ShiftT) = @splat(shift);
    return v128FromVec(i32, 4, lanes >> shifts);
}

pub fn i32x4ShrU(value: V128, amount: u32) V128 {
    const ShiftT = std.math.Log2Int(u32);
    const shift: ShiftT = @intCast(amount % @bitSizeOf(u32));
    const lanes = vecFromV128(u32, 4, value);
    const shifts: @Vector(4, ShiftT) = @splat(shift);
    return v128FromVec(u32, 4, lanes >> shifts);
}

pub fn i32x4Splat(value: i32) V128 {
    return v128FromVec(i32, 4, @as(I32x4, @splat(value)));
}

pub fn i32x4Sub(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i32, 4, lhs);
    const b = vecFromV128(i32, 4, rhs);
    return v128FromVec(i32, 4, a -% b);
}

pub fn i32x4TruncSatF32x4S(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const lane = readLane(f32, value.bytes, @intCast(i));
        writeLane(i32, &out, @intCast(i), helper.truncateSaturateInto(i32, lane));
    }
    return v128FromBytes(out);
}

pub fn i32x4TruncSatF32x4U(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..4) |i| {
        const lane = readLane(f32, value.bytes, @intCast(i));
        const bits = helper.truncateSaturateInto(u32, lane);
            writeLane(i32, &out, @intCast(i), @bitCast(bits));
    }
    return v128FromBytes(out);
}

pub fn i32x4TruncSatF64x2SZero(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const lane = readLane(f64, value.bytes, @intCast(i));
        writeLane(i32, &out, @intCast(i), helper.truncateSaturateInto(i32, lane));
    }
    return v128FromBytes(out);
}

pub fn i32x4TruncSatF64x2UZero(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const lane = readLane(f64, value.bytes, @intCast(i));
        const bits = helper.truncateSaturateInto(u32, lane);
            writeLane(i32, &out, @intCast(i), @bitCast(bits));
    }
    return v128FromBytes(out);
}

pub fn i64x2Abs(value: V128) V128 {
    const lanes = vecFromV128(i64, 2, value);
    const zero: I64x2 = @splat(0);
    const results: I64x2 = @select(i64, lanes < zero, zero -% lanes, lanes);
    return v128FromVec(i64, 2, results);
}

pub fn i64x2Add(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i64, 2, lhs);
    const b = vecFromV128(i64, 2, rhs);
    return v128FromVec(i64, 2, a +% b);
}

pub fn i64x2AllTrue(value: V128) bool {
    const lanes = vecFromV128(i64, 2, value);
    const zero: I64x2 = @splat(0);
    return @reduce(.And, lanes != zero);
}

pub fn i64x2Bitmask(value: V128) i32 {
    const lanes = vecFromV128(i64, 2, value);
    const zero: I64x2 = @splat(0);
    const sign_bits: @Vector(2, u1) = @bitCast(lanes < zero);
    const MaskInt = std.meta.Int(.unsigned, 2);
    const mask_uint: MaskInt = @bitCast(sign_bits);
    return @as(i32, @intCast(mask_uint));
}

pub fn i64x2Eq(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i64, 2, lhs);
    const b = vecFromV128(i64, 2, rhs);
    const mask = a == b;
    return vectorMaskToV128(i64, 2, mask);
}

pub fn i64x2ExtendHighI32x4S(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const lane = readLane(i32, value.bytes, @intCast(2 + i));
        const result: i64 = if (true) @as(i64, lane) else @as(i64, @intCast(lane));
        writeLane(i64, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i64x2ExtendHighI32x4U(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const lane = readLane(i32, value.bytes, @intCast(2 + i));
        const result: i64 = if (true) @as(i64, lane) else @as(i64, @intCast(lane));
        writeLane(i64, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i64x2ExtendLowI32x4S(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const lane = readLane(i32, value.bytes, @intCast(0 + i));
        const result: i64 = if (true) @as(i64, lane) else @as(i64, @intCast(lane));
        writeLane(i64, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i64x2ExtendLowI32x4U(value: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const lane = readLane(i32, value.bytes, @intCast(0 + i));
        const result: i64 = if (true) @as(i64, lane) else @as(i64, @intCast(lane));
        writeLane(i64, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i64x2ExtmulHighI32x4S(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const a = readLane(i32, lhs.bytes, @intCast(2 + i));
        const b = readLane(i32, rhs.bytes, @intCast(2 + i));
        const result: i64 = @as(i64, a) * @as(i64, b);
        writeLane(i64, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i64x2ExtmulHighI32x4U(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const a = readLane(i32, lhs.bytes, @intCast(2 + i));
        const b = readLane(i32, rhs.bytes, @intCast(2 + i));
        const result: i64 = @as(i64, a) * @as(i64, b);
        writeLane(i64, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i64x2ExtmulLowI32x4S(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const a = readLane(i32, lhs.bytes, @intCast(0 + i));
        const b = readLane(i32, rhs.bytes, @intCast(0 + i));
        const result: i64 = @as(i64, a) * @as(i64, b);
        writeLane(i64, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i64x2ExtmulLowI32x4U(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..2) |i| {
        const a = readLane(i32, lhs.bytes, @intCast(0 + i));
        const b = readLane(i32, rhs.bytes, @intCast(0 + i));
        const result: i64 = @as(i64, a) * @as(i64, b);
        writeLane(i64, &out, @intCast(i), result);
    }
    return v128FromBytes(out);
}

pub fn i64x2GeS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i64, 2, lhs);
    const b = vecFromV128(i64, 2, rhs);
    const mask = a >= b;
    return vectorMaskToV128(i64, 2, mask);
}

pub fn i64x2GtS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i64, 2, lhs);
    const b = vecFromV128(i64, 2, rhs);
    const mask = a > b;
    return vectorMaskToV128(i64, 2, mask);
}

pub fn i64x2LeS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i64, 2, lhs);
    const b = vecFromV128(i64, 2, rhs);
    const mask = a <= b;
    return vectorMaskToV128(i64, 2, mask);
}

pub fn i64x2LtS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i64, 2, lhs);
    const b = vecFromV128(i64, 2, rhs);
    const mask = a < b;
    return vectorMaskToV128(i64, 2, mask);
}

pub fn i64x2Mul(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i64, 2, lhs);
    const b = vecFromV128(i64, 2, rhs);
    return v128FromVec(i64, 2, a *% b);
}

pub fn i64x2Ne(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i64, 2, lhs);
    const b = vecFromV128(i64, 2, rhs);
    const mask = a != b;
    return vectorMaskToV128(i64, 2, mask);
}

pub fn i64x2Neg(value: V128) V128 {
    const lanes = vecFromV128(i64, 2, value);
    const zero: I64x2 = @splat(0);
    return v128FromVec(i64, 2, zero -% lanes);
}

pub fn i64x2Shl(value: V128, amount: u32) V128 {
    const ShiftT = std.math.Log2Int(i64);
    const shift: ShiftT = @intCast(amount % @bitSizeOf(i64));
    const lanes = vecFromV128(i64, 2, value);
    const shifts: @Vector(2, ShiftT) = @splat(shift);
    return v128FromVec(i64, 2, lanes << shifts);
}

pub fn i64x2ShrS(value: V128, amount: u32) V128 {
    const ShiftT = std.math.Log2Int(i64);
    const shift: ShiftT = @intCast(amount % @bitSizeOf(i64));
    const lanes = vecFromV128(i64, 2, value);
    const shifts: @Vector(2, ShiftT) = @splat(shift);
    return v128FromVec(i64, 2, lanes >> shifts);
}

pub fn i64x2ShrU(value: V128, amount: u32) V128 {
    const ShiftT = std.math.Log2Int(u64);
    const shift: ShiftT = @intCast(amount % @bitSizeOf(u64));
    const lanes = vecFromV128(u64, 2, value);
    const shifts: @Vector(2, ShiftT) = @splat(shift);
    return v128FromVec(u64, 2, lanes >> shifts);
}

pub fn i64x2Splat(value: i64) V128 {
    return v128FromVec(i64, 2, @as(I64x2, @splat(value)));
}

pub fn i64x2Sub(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i64, 2, lhs);
    const b = vecFromV128(i64, 2, rhs);
    return v128FromVec(i64, 2, a -% b);
}

pub fn i8x16Abs(value: V128) V128 {
    const lanes = vecFromV128(i8, 16, value);
    const zero: I8x16 = @splat(0);
    const results: I8x16 = @select(i8, lanes < zero, zero -% lanes, lanes);
    return v128FromVec(i8, 16, results);
}

pub fn i8x16Add(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i8, 16, lhs);
    const b = vecFromV128(i8, 16, rhs);
    return v128FromVec(i8, 16, a +% b);
}

pub fn i8x16AddSatS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i8, 16, lhs);
    const b = vecFromV128(i8, 16, rhs);
    return v128FromVec(i8, 16, a +| b);
}

pub fn i8x16AddSatU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u8, 16, lhs);
    const b = vecFromV128(u8, 16, rhs);
    return v128FromVec(u8, 16, a +| b);
}

pub fn i8x16AllTrue(value: V128) bool {
    const lanes = vecFromV128(i8, 16, value);
    const zero: I8x16 = @splat(0);
    return @reduce(.And, lanes != zero);
}

pub fn i8x16AvgrU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u8, 16, lhs);
    const b = vecFromV128(u8, 16, rhs);
    const ShiftT = std.math.Log2Int(u8);
    const shifts: @Vector(16, ShiftT) = @splat(1);
    return v128FromVec(u8, 16, (a | b) - ((a ^ b) >> shifts));
}

pub fn i8x16Bitmask(value: V128) i32 {
    const lanes = vecFromV128(i8, 16, value);
    const zero: I8x16 = @splat(0);
    const sign_bits: @Vector(16, u1) = @bitCast(lanes < zero);
    const MaskInt = std.meta.Int(.unsigned, 16);
    const mask_uint: MaskInt = @bitCast(sign_bits);
    return @as(i32, @intCast(mask_uint));
}

pub fn i8x16Eq(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i8, 16, lhs);
    const b = vecFromV128(i8, 16, rhs);
    const mask = a == b;
    return vectorMaskToV128(i8, 16, mask);
}

pub fn i8x16GeS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i8, 16, lhs);
    const b = vecFromV128(i8, 16, rhs);
    const mask = a >= b;
    return vectorMaskToV128(i8, 16, mask);
}

pub fn i8x16GeU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u8, 16, lhs);
    const b = vecFromV128(u8, 16, rhs);
    const mask = a >= b;
    return vectorMaskToV128(u8, 16, mask);
}

pub fn i8x16GtS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i8, 16, lhs);
    const b = vecFromV128(i8, 16, rhs);
    const mask = a > b;
    return vectorMaskToV128(i8, 16, mask);
}

pub fn i8x16GtU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u8, 16, lhs);
    const b = vecFromV128(u8, 16, rhs);
    const mask = a > b;
    return vectorMaskToV128(u8, 16, mask);
}

pub fn i8x16LeS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i8, 16, lhs);
    const b = vecFromV128(i8, 16, rhs);
    const mask = a <= b;
    return vectorMaskToV128(i8, 16, mask);
}

pub fn i8x16LeU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u8, 16, lhs);
    const b = vecFromV128(u8, 16, rhs);
    const mask = a <= b;
    return vectorMaskToV128(u8, 16, mask);
}

pub fn i8x16LtS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i8, 16, lhs);
    const b = vecFromV128(i8, 16, rhs);
    const mask = a < b;
    return vectorMaskToV128(i8, 16, mask);
}

pub fn i8x16LtU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u8, 16, lhs);
    const b = vecFromV128(u8, 16, rhs);
    const mask = a < b;
    return vectorMaskToV128(u8, 16, mask);
}

pub fn i8x16MaxS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i8, 16, lhs);
    const b = vecFromV128(i8, 16, rhs);
    return v128FromVec(i8, 16, @select(i8, a > b, a, b));
}

pub fn i8x16MaxU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u8, 16, lhs);
    const b = vecFromV128(u8, 16, rhs);
    return v128FromVec(u8, 16, @select(u8, a > b, a, b));
}

pub fn i8x16MinS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i8, 16, lhs);
    const b = vecFromV128(i8, 16, rhs);
    return v128FromVec(i8, 16, @select(i8, a < b, a, b));
}

pub fn i8x16MinU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u8, 16, lhs);
    const b = vecFromV128(u8, 16, rhs);
    return v128FromVec(u8, 16, @select(u8, a < b, a, b));
}

pub fn i8x16NarrowI16x8S(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..8) |i| {
        writeLane(i8, &out, @intCast(i), narrowLane(i16, i8, readLane(i16, lhs.bytes, @intCast(i)), true));
        writeLane(i8, &out, @intCast(8 + i), narrowLane(i16, i8, readLane(i16, rhs.bytes, @intCast(i)), true));
    }
    return v128FromBytes(out);
}

pub fn i8x16NarrowI16x8U(lhs: V128, rhs: V128) V128 {
    var out = std.mem.zeroes([16]u8);
    inline for (0..8) |i| {
        writeLane(i8, &out, @intCast(i), narrowLane(i16, i8, readLane(i16, lhs.bytes, @intCast(i)), true));
        writeLane(i8, &out, @intCast(8 + i), narrowLane(i16, i8, readLane(i16, rhs.bytes, @intCast(i)), true));
    }
    return v128FromBytes(out);
}

pub fn i8x16Ne(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i8, 16, lhs);
    const b = vecFromV128(i8, 16, rhs);
    const mask = a != b;
    return vectorMaskToV128(i8, 16, mask);
}

pub fn i8x16Neg(value: V128) V128 {
    const lanes = vecFromV128(i8, 16, value);
    const zero: I8x16 = @splat(0);
    return v128FromVec(i8, 16, zero -% lanes);
}

pub fn i8x16Shl(value: V128, amount: u32) V128 {
    const ShiftT = std.math.Log2Int(i8);
    const shift: ShiftT = @intCast(amount % @bitSizeOf(i8));
    const lanes = vecFromV128(i8, 16, value);
    const shifts: @Vector(16, ShiftT) = @splat(shift);
    return v128FromVec(i8, 16, lanes << shifts);
}

pub fn i8x16ShrS(value: V128, amount: u32) V128 {
    const ShiftT = std.math.Log2Int(i8);
    const shift: ShiftT = @intCast(amount % @bitSizeOf(i8));
    const lanes = vecFromV128(i8, 16, value);
    const shifts: @Vector(16, ShiftT) = @splat(shift);
    return v128FromVec(i8, 16, lanes >> shifts);
}

pub fn i8x16ShrU(value: V128, amount: u32) V128 {
    const ShiftT = std.math.Log2Int(u8);
    const shift: ShiftT = @intCast(amount % @bitSizeOf(u8));
    const lanes = vecFromV128(u8, 16, value);
    const shifts: @Vector(16, ShiftT) = @splat(shift);
    return v128FromVec(u8, 16, lanes >> shifts);
}

pub fn i8x16Splat(value: i8) V128 {
    return v128FromVec(i8, 16, @as(I8x16, @splat(value)));
}

pub fn i8x16Sub(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i8, 16, lhs);
    const b = vecFromV128(i8, 16, rhs);
    return v128FromVec(i8, 16, a -% b);
}

pub fn i8x16SubSatS(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(i8, 16, lhs);
    const b = vecFromV128(i8, 16, rhs);
    return v128FromVec(i8, 16, a -| b);
}

pub fn i8x16SubSatU(lhs: V128, rhs: V128) V128 {
    const a = vecFromV128(u8, 16, lhs);
    const b = vecFromV128(u8, 16, rhs);
    return v128FromVec(u8, 16, a -| b);
}
